// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Link$ReactTemplate = require("./Link.bs.js");

var header = Css.style(/* :: */[
      Css.position(Css.fixed),
      /* :: */[
        Css.display(/* flex */-1010954439),
        /* :: */[
          Css.top(Css.px(0)),
          /* :: */[
            Css.left(Css.px(0)),
            /* :: */[
              Css.flexDirection(Css.column),
              /* :: */[
                Css.alignItems(Css.flexStart),
                /* :: */[
                  Css.fontFamily("mr-eaves-xl-modern, sans-serif"),
                  /* :: */[
                    Css.paddingLeft(Css.vw(10.0)),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var Styles = /* module */[/* header */header];

var component = ReasonReact.statelessComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: header
                        }, ReasonReact.element(undefined, undefined, Link$ReactTemplate.make(/* array */[React.createElement("h1", undefined, "Elysium")], undefined, "/")), ReasonReact.element(undefined, undefined, Link$ReactTemplate.make(/* array */[React.createElement("h2", undefined, "Submit a project")], undefined, "/submit")));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* header Not a pure module */
