// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Link$ReactTemplate = require("./Link.bs.js");

function project(projectColor) {
  return Css.style(/* :: */[
              Css.display(/* flex */-1010954439),
              /* :: */[
                Css.flexDirection(Css.column),
                /* :: */[
                  Css.alignItems(Css.center),
                  /* :: */[
                    Css.justifyContent(Css.center),
                    /* :: */[
                      Css.minHeight(Css.px(300)),
                      /* :: */[
                        Css.minWidth(Css.px(400)),
                        /* :: */[
                          Css.marginBottom(Css.px(200)),
                          /* :: */[
                            Css.backgroundColor(Css.hex(projectColor)),
                            /* :: */[
                              /* `transition */[
                                -659583595,
                                "box-shadow 0.2s"
                              ],
                              /* :: */[
                                Css.hover(/* :: */[
                                      Css.boxShadow(Css.px(7), Css.px(7), Css.px(27), Css.px(-2), undefined, Css.rgba(0, 0, 0, 0.75)),
                                      /* [] */0
                                    ]),
                                /* :: */[
                                  Css.color(Css.hex("FFFFFF")),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var name = Css.style(/* :: */[
      Css.textDecoration(Css.none),
      /* [] */0
    ]);

var Styles = /* module */[
  /* project */project,
  /* name */name
];

var component = ReasonReact.statelessComponent("Project");

function make(_children, name$1, slug, color) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Link$ReactTemplate.make(/* array */[React.createElement("h1", {
                                    className: name
                                  }, name$1)], project(color), "/projects/" + slug));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* name Not a pure module */
