// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Project$ReactTemplate = require("./Project.bs.js");

var projects = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(Css.column),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* projects */projects];

var component = ReasonReact.statelessComponent("Projects");

var projects$1 = /* :: */[
  "Aletheia",
  /* :: */[
    "Saber",
    /* :: */[
      "Website",
      /* :: */[
        "Org Site",
        /* :: */[
          "Stuyspec",
          /* :: */[
            "Greedux",
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: projects
                        }, $$Array.of_list(List.map((function (title) {
                                    return ReasonReact.element(undefined, undefined, Project$ReactTemplate.make(/* array */[], title));
                                  }), projects$1)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.projects = projects$1;
exports.make = make;
/* projects Not a pure module */
