// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function projectToJs(param) {
  return {
          id: param[/* id */0],
          name: param[/* name */1],
          color: param[/* color */2],
          slug: param[/* slug */3],
          description: param[/* description */4]
        };
}

function projectFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* name */param.name,
          /* color */param.color,
          /* slug */param.slug,
          /* description */param.description
        ];
}

exports.projectToJs = projectToJs;
exports.projectFromJs = projectFromJs;
/* No side effect */
